# Generated by Django 6.0.2 on 2026-02-23 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Betslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('odd', models.CharField(max_length=100)),
                ('booking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='superfixed.betslip')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
