# Generated by Django 6.0.2 on 2026-02-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superfixed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='channel',
            field=models.CharField(blank=True, choices=[('ussd', 'ussd'), ('web', 'web')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('sccess', 'success'), ('failed', 'failed')], max_length=100, null=True),
        ),
    ]
