# Generated by Django 6.0.2 on 2026-02-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superfixed', '0002_slipcategory_betslip_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandaccount',
            name='dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandaccount',
            name='index_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
