# Generated by Django 6.0.2 on 2026-02-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superfixed', '0002_transaction_channel_transaction_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
