# Generated by Django 6.0.2 on 2026-02-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superfixed', '0003_brandaccount_dec_brandaccount_index_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandaccount',
            name='abbr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
