# Generated by Django 6.0.2 on 2026-02-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superfixed', '0004_alter_brandaccount_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandaccount',
            name='slip_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
